datawarehouse:
  outputs:
    dev:
      type: postgres
      dbname: "{{ env_var('DB_NAME_PROD') }}"
      host: "{{ env_var('DB_HOST_PROD') }}"
      pass: "{{ env_var('DB_PASS_PROD') }}"
      port: 5432
      schema: "{{ env_var('DB_SCHEMA_PROD') }}"
      threads: 1
      user: "{{ env_var('DB_USER_PROD') }}"
  target: dev
