version: 2

models:
  - name: stg_commodities
    description: "Table from staging with commodities prices"
    columns:
      - name: date
        description: "Date AAAA-MM-DD"
      - name: close_price
        description: "price of commoditiy"
      - name: symbol
        description: "Commodity Symbol - yahoo finance"

  - name: stg_movimentacao_commodities
    description: "Table from staging with commodities orders"
    columns:
      - name: date
        description: "Date AAAA-MM-DD"
      - name: symbol
        description: "Commodity Symbol - yahoo finance"
      - name: action
        description: "buy or sell"
      - name: quantity
        description: quantity ordered